import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Script from 'next/script';
import Link from 'next/link';
import { AntdRegistry } from '@ant-design/nextjs-registry';
import './globals.css';

export const metadata: Metadata = {
  title: '首页',
  description: 'Generated by create next app',
};
export default function RootLayout({ children, team }: { children: React.ReactNode; team: React.ReactNode }) {
  return (
    <html lang='zh'>
      <body className='min-h-screen bg-green-100 '>
        <Link href='/'>
          <h1 className=' text-center font-bold text-2xl bg-slate-500 py-2 mb-2'>根-Layout</h1>
        </Link>
        <AntdRegistry>{children}</AntdRegistry>
        {/* {team} */}
        <Script async src='https://www.googletagmanager.com/gtag/js?id=AW-11217955271' />
      </body>
    </html>
  );
}
