import type { Metadata } from 'next';
import { AntdRegistry } from '@ant-design/nextjs-registry';
import { useState } from 'react';
import Link from 'next/link';
// import { useSelectedLayoutSegment } from 'next/navigation';
export const metadata: Metadata = {
  title: '面板',
  description: 'Generated by create next app',
};

export default function DashboardLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Record<string, any>;
}) {
  // const ret = useSelectedLayoutSegment();
  // console.log('==ret====>', ret);
  // console.log('==params====>', params);

  return (
    <>
      <h1>面板-Layout</h1>
      <hr />

      {children}
    </>
  );
}
