import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: '面板',
  description: 'Generated by create next app',
};

export default function DashboardLayout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <h1>面板-Layout</h1>
      <hr />
      {children}
    </>
  );
}
